### ISSUE TITLE
Support for json?

### ISSUE THREAD

**Issue by zacharynevin** [t3rminus/spreedly-client#1]
If you use the `.json` as the content type in the request instead of `.xml`, you will get a json response from Spreedly (e.g. using `/authorize.json` instead of `/authorize.xml`). 

Can we add support for this? It seems a bit overkill to take the `xmls response and parse it to`json`when you can simply get the`json` response from the API.

**Comment by t3rminus** [comment]
Thanks for the heads up. This was either not available or not (well) documented when I started work on this. 

Expect an update in the next few days!

**Comment by t3rminus** [comment]
As of v0.2.0 it is now using the json endpoints
